services:
  api:
    container_name: "forumly"
    build: .
    env_file: .env
    expose:
      - 4000
    depends_on:
      - db

  db:
    container_name: "mongodb"
    image: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: forumly_password
    expose:
      - 27017

  nginx:
    container_name: "nginx"
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api
      - db

volumes:
  mongo_data:
